from datetime import datetime, timedelta

from fastapi import HTTPException

from schemas.task_schema import TaskCreate, TaskDetail, TaskUpdate


# 서버가 실행되는 동안만 유지되는 가짜 데이터
def task_get_all() -> list[TaskDetail]:
    result = [
        {
            "id": 1,
            "project_id": 1,
            "title": "프로젝트 테이블 설계",
            "description": "프로젝트 CRUD를 위한 테이블과 컬럼을 설계합니다.",
            "assignee": "김민수",
            "status": "DONE",
            "priority": "HIGH",
            "due_date": "2026-07-21",
            "created_at": "2026-07-10T09:00:00",
            "updated_at": "2026-07-20T15:30:00",
        },
        {
            "id": 2,
            "project_id": 1,
            "title": "업무 CRUD API 구현",
            "description": "업무 생성, 조회, 수정, 삭제 API를 구현합니다.",
            "assignee": "박현우",
            "status": "IN_PROGRESS",
            "priority": "HIGH",
            "due_date": "2026-08-02",
            "created_at": "2026-07-15T10:00:00",
            "updated_at": "2026-07-27T13:20:00",
        },
        {
            "id": 3,
            "project_id": 1,
            "title": "칸반 보드 화면 구현",
            "description": "업무 상태별로 TODO, 진행 중, 완료를 표시합니다.",
            "assignee": "이지수",
            "status": "IN_PROGRESS",
            "priority": "MEDIUM",
            "due_date": "2026-08-05",
            "created_at": "2026-07-17T11:30:00",
            "updated_at": "2026-07-28T09:10:00",
        },
        {
            "id": 4,
            "project_id": 1,
            "title": "상태별 업무 차트 구현",
            "description": "업무 상태 비율을 도넛 차트로 표시합니다.",
            "assignee": "최서연",
            "status": "TODO",
            "priority": "MEDIUM",
            "due_date": "2026-08-08",
            "created_at": "2026-07-25T14:00:00",
            "updated_at": "2026-07-25T14:00:00",
        },
        {
            "id": 5,
            "project_id": 2,
            "title": "상품 목록 API 구현",
            "description": "상품 목록과 카테고리 필터 API를 구현합니다.",
            "assignee": "김민수",
            "status": "DONE",
            "priority": "HIGH",
            "due_date": "2026-07-20",
            "created_at": "2026-07-08T09:30:00",
            "updated_at": "2026-07-19T16:00:00",
        },
        {
            "id": 6,
            "project_id": 2,
            "title": "장바구니 기능 구현",
            "description": "상품 추가, 수량 변경, 삭제 기능을 구현합니다.",
            "assignee": "박현우",
            "status": "IN_PROGRESS",
            "priority": "HIGH",
            "due_date": "2026-08-01",
            "created_at": "2026-07-18T10:20:00",
            "updated_at": "2026-07-27T17:30:00",
        },
        {
            "id": 7,
            "project_id": 2,
            "title": "상품 검색 화면 구현",
            "description": "상품 이름으로 검색하는 화면을 구현합니다.",
            "assignee": "이지수",
            "status": "TODO",
            "priority": "LOW",
            "due_date": "2026-08-10",
            "created_at": "2026-07-26T13:00:00",
            "updated_at": "2026-07-26T13:00:00",
        },
        {
            "id": 8,
            "project_id": 2,
            "title": "반응형 디자인 적용",
            "description": "모바일과 태블릿 화면에 맞게 UI를 조정합니다.",
            "assignee": "최서연",
            "status": "TODO",
            "priority": "MEDIUM",
            "due_date": "2026-08-12",
            "created_at": "2026-07-27T15:40:00",
            "updated_at": "2026-07-27T15:40:00",
        },
        {
            "id": 9,
            "project_id": 3,
            "title": "행사 등록 API 구현",
            "description": "관리자가 행사를 등록하는 API를 구현합니다.",
            "assignee": "김민수",
            "status": "DONE",
            "priority": "HIGH",
            "due_date": "2026-07-22",
            "created_at": "2026-07-11T09:00:00",
            "updated_at": "2026-07-21T18:00:00",
        },
        {
            "id": 10,
            "project_id": 3,
            "title": "참가 신청 폼 구현",
            "description": "사용자가 행사 참가를 신청하는 폼을 구현합니다.",
            "assignee": "이지수",
            "status": "IN_PROGRESS",
            "priority": "HIGH",
            "due_date": "2026-08-03",
            "created_at": "2026-07-20T11:10:00",
            "updated_at": "2026-07-28T10:00:00",
        },
        {
            "id": 11,
            "project_id": 3,
            "title": "참가자 목록 조회 API",
            "description": "행사별 참가자 정보를 조회하는 API를 구현합니다.",
            "assignee": "박현우",
            "status": "TODO",
            "priority": "MEDIUM",
            "due_date": "2026-08-06",
            "created_at": "2026-07-24T14:30:00",
            "updated_at": "2026-07-24T14:30:00",
        },
        {
            "id": 12,
            "project_id": 3,
            "title": "행사 참가 현황 차트",
            "description": "행사별 참가 신청 수를 막대그래프로 표시합니다.",
            "assignee": "최서연",
            "status": "TODO",
            "priority": "LOW",
            "due_date": "2026-08-14",
            "created_at": "2026-07-28T09:40:00",
            "updated_at": "2026-07-28T09:40:00",
        },
    ]

    return result
